### ISSUE TITLE
Provide rule meta information as JSON

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/restful-api-guidelines#446]
**As a** developer of the API Portal
**I want to** have an overview of all rules from the Guidelines as JSON
**So that** I can consume this information in an automatic manner and provide this information to the API Portal users

### Acceptance criteria
- [x] JSON file is created and is accessible under https://opensource.zalando.com/restful-api-guidelines/rules
- [x] File contains rule `title` and `id`
- [x] The content of the file is generated during the build
